# Gunakan base image Python versi terbaru
FROM python:3.9-slim

# Set direktori kerja di container
WORKDIR /app

# Salin file requirements.txt ke dalam container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file ke direktori kerja
COPY . .

# Expose port yang digunakan oleh Flask
EXPOSE 8001

# Jalankan aplikasi
CMD ["python", "app.py"]
